### ISSUE TITLE
ET: requesting bot to follow player by vsay command

### ISSUE THREAD

**Issue by mittermichal** [jswigart/omni-bot#13]
hello,
i was looking though source and i found that it should be implemented,
but doing v31 ingame (Follow me!) doesn't seem to work, meanwhile v21 and v22 (Need medic/ammo) work
does it have to be explicitly implemented in game mod?
Regards
Kimi|AHK

**Comment by plastovicka** [comment]
Medic and ammo commands are implemented in script et/scripts/goals/goal_deliversupplies.gm. If you want bots to follow you, you can use script goal_fireteam.gm. It is disabled by default and can be enabled in the config file et/user/omni-bot.cfg. You must bind some key to Fire-Team Admin in the ET options. Then you can create a new fire team and invite players. Bots will always accept your invitation. They will automatically follow you if they don't have anything more important to do.

**Comment by mittermichal** [comment]
thank you!
i'm checking it out, lot of cool stuff there!
