### ISSUE TITLE
Several important wiki pages missing

### ISSUE THREAD

**Issue by wallabra** [jswigart/omni-bot#14]
Hello. I have decided to return to Return to Castle Wolfenstein (ha!), but have been unsuccessful in finding the installation and usage procedures of the Omni-Bot. When I found this repository, one of the first things I tried was open the wiki, however I had little success.

Following my intuition has helped me load the Omni-Bots from the Mods menu (under Options, in the main menu), however they never spawn, even after setting CVars like `bot_enable 1` and `bot_minplayers 20`. Do I need to open a map with `\devmap` specifically? If so, is there a way to spawn the bots whilst still opening the listen server from the standard Multiplayer menu?

**Tip:** if you simply fear that writing the wiki now could make it invalid and misleading for future releases, it can help writing a changelog, and adding "wiki update" milestones (in the Issues tab) for each version released. Better yet maybe, make a summary of what specific changes may be needed to the wiki in said changelog, pruning more technical details that would go better in the auto-generated documentation you already have.

Alternatively, put the documentation in the repository itself instead, and ditch the wiki (or link to said docs in the GitHub Pages website). It can be as simple as using a Markdown renderer (e.g. [MkDocs](https://www.mkdocs.org/)) to generate necessary HTML in the gh-pages branch (through a git hook script or some other sort of update script), while keeping the original Markdown documentation in master so it can be viewed properly from GitHub's code browser.

Cheers! :)

**Comment by Gustavo6046** [comment]
Addendum #1. I'm actually on Linux, and using iortcw.

**Comment by jswigart** [comment]
I have the wiki enabled here on github because I had planned/hoped someone might be open to taking the reigns on building up a new repository of knowledge here in the bots new home. I know it sucks to not have access to the old bot site forums and such, but so far I have been unable to get my hands on that old data. I did not pay for that hosting nor have access to its administration, and it is difficult to get in touch with the one who did.

**Comment by Gustavo6046** [comment]
Ah. I would like to try and volunteer for it, adding what I can make out of what experience I can get out of this. As for the old webpage, did you try [the Internet Archive](web.archive.org/http://www.omni-bot.com/wiki/index.php?title=Installing_Omni-bot)? From there you can copy the text from the content div, maybe copy the HTML as a reference for the Markdown version. It is most likely the best shot you have at it.

Either way, perhaps continued support to the issue of spawning the bots would be best in a separate issue, or through emails. It does work with Wine and the standard WolfMP executable, so it's probably an iortcw issue, anyway. Most likely trying to just load DLLs wacks it up, hah!

**Comment by jswigart** [comment]
I'm inviting you as a collaborator and I think that will give you free
reign to iterate the github wiki to fill in whatever is missing, port over
whatever is useful from the internet archive, etc.

**Comment by plastovicka** [comment]
Full HTML export of Omni-bot 0.85 wiki can be downloaded from [dropbox](https://www.dropbox.com/s/i2rw1fsqo31yjki/Omni-Bot%20Wiki%20%28ET%29%20-%209th%20May%202017.7z?dl=0). 
XML markup of Omni-bot 0.87 can be downloaded from my [Google drive](https://drive.google.com/file/d/1IzS1vHQR-JmJwin-KSzb2a3ur75NwF4A/view?usp=sharing).
I think it would be too much work and waste of time to covert the wiki to GitHub pages format. @hellreturm offered to host the wiki on his [silEnT mod website](https://mygamingtalk.com).
I have installed MediaWiki on my PC so I could share its MySQL database. But I don't have GameMonkey scripts syntax highlighter. All scripts are displayed on one line and are unreadable. Does anybody know how to install and configure syntax highlighter in MediaWiki ? We already have syntax highlighters for Notepad++ and other text editors.

**Comment by Mateos81** [comment]
That DropBox link looks like an old mine, here's a more recent one from 2020 (comments section): https://app.assembla.com/spaces/omnibot/subversion/commits/3528

**Comment by Gustavo6046** [comment]
Thank you! I can't wait to delve into the madly maniac and awesomely awkward world of blowing up the beach walls with a squad of 7 other bots! _(Side note, I've always noticed mp-beach is awfully similar to Unreal Tournament's AS-Overlord map.)_

I will figure out, with this additional material, how to add those bots to a game, then I will add to the wiki with whatever experience I can gather out of it.

**Comment by Gustavo6046** [comment]
Hm, that is actually technical documentation. I can't find other docs there. I remember there also being more general documentation in that same website, though. I truly remember that little doll guy on the top left there...

**Comment by plastovicka** [comment]
Running iortcw with bots is easy:
- Download and extract [iortcw-1.51c-linux-x86.zip](https://github.com/iortcw/iortcw/releases) and [omni-bot_0_87_RTCW.zip](https://github.com/jswigart/omni-bot/releases)
- ./iowolfmp.x86 +set fs_game omnibot +set omnibot_path omni-bot
- load any map, for example /map mp_beach
- type command /bot maxbots 15

**Comment by Gustavo6046** [comment]
The command 'bot' was missing from my iortcw version. Maybe it has to do with the latter being x86_64 (AMD64), or some specific version thereof? That's for another issue, though; besides, I probably am missing something obvious!

Thank you for the suggestions, though! I will try again, but this time I'll follow the steps (save for the first one) to see if it works any better. Then I'll try again with the x86 (IA32) build of iortcw.

**Comment by HarryHomers** [comment]
I can offer up some web space, if that would be helpful ?

**Comment by plastovicka** [comment]
We have a new discussion forum at https://mygamingtalk.com/forums/forum/82-omnibot-development-and-discussion/

**Comment by Chucky-eng** [comment]
ok thank you so much

**Comment by Gustavo6046** [comment]
> We have a new discussion forum at https://mygamingtalk.com/forums/forum/82-omnibot-development-and-discussion/

It gives an error whenever I try to access it.
"You do not have permission to view this forum."

Is that intentional?

**Comment by Gustavo6046** [comment]
> The "bot" command is built into the mod, so if it was missing then the mod doesn't have bot support. Even if Omni-bot isn't installed that command will be present, and just print an error if the bot is not loaded.

Mod? Are you talking about iortcw? It is just a source port of Return to Castle Wolfenstein, which reuses some of the ioquake3 code and whatnot. I think it has more to do with mismatching architectures. I will take a more in-depth look when I can.

**Comment by plastovicka** [comment]
> > We have a new discussion forum at https://mygamingtalk.com/forums/forum/82-omnibot-development-and-discussion/
> 
> It gives an error whenever I try to access it.
> "You do not have permission to view this forum."

The forum is accessible only for registered users. Click the _Create Account_ button in the upper right corner.

**Comment by plastovicka** [comment]
If you have installed 64-bit iorctw ([iortcw-1.51c-linux-x86_64.zip](https://github.com/iortcw/iortcw/releases)), you must install 64-bit omni-bot ([omni-bot_0_87_RTCW_64bit.zip](https://github.com/jswigart/omni-bot/releases/tag/0.87)).

**Comment by Mateos81** [comment]
> The forum is accessible only for registered users. Click the _Create Account_ button in the upper right corner.

Would it be possible to give this sub-forum the read access to non-registered users?
So it could be read without the account requirement

**Comment by Gustavo6046** [comment]
> > > We have a new discussion forum at https://mygamingtalk.com/forums/forum/82-omnibot-development-and-discussion/
> > 
> > 
> > It gives an error whenever I try to access it.
> > "You do not have permission to view this forum."
> 
> The forum is accessible only for registered users. Click the _Create Account_ button in the upper right corner.

Ah, I see, thanks!


> If you have installed 64-bit iorctw ([iortcw-1.51c-linux-x86_64.zip](https://github.com/iortcw/iortcw/releases)), you must install 64-bit omni-bot ([omni-bot_0_87_RTCW_64bit.zip](https://github.com/jswigart/omni-bot/releases/tag/0.87)).

I think I had that one, though. Not the 32-bit versin. Or maybe not. Odd. Go figure. :P
But thank you!



> > The forum is accessible only for registered users. Click the _Create Account_ button in the upper right corner.
> 
> Would it be possible to give this sub-forum the read access to non-registered users?
> So it could be read without the account requirement

That sounds like a nifty idea! It would also allow archival by bots/crawlers like the Internet Archive's.

**Comment by plastovicka** [comment]
I created a new online wiki on [https://omnibot-enemy-territory.fandom.com](https://omnibot-enemy-territory.fandom.com/wiki/Omni-Bot_Enemy_Territory_Wiki)

**Comment by plastovicka** [comment]
Wiki has been moved to [https://mygamingtalk.com/wiki](https://mygamingtalk.com/wiki/OMNIBOT_-_Enemy_Territory_Modification)
