### ISSUE TITLE
Where to find omnibiot waypoints

### ISSUE THREAD

**Issue by Chucky-eng** [jswigart/omni-bot#16]
Been trying to find omnibot waypoints for these maps if anyone can help would be great 
some of the maps dont have waypoints at the mpment so please dont pick these maps _M4CHiN3  
blitz_final 
adlernest_desert 
CaptureTheBox_R1 
ea_base2 
 ctf_poola 
complex_b3 
osiris_final 
mario_b3 works  
 fp_jaden 
kta_massacre 
king_of_the_hill 
London goldrush

**Comment by Mateos81** [comment]
For these ones, I believe it's just a mere re-texturing, so you can copy/paste/rename the original ones and see:
adlernest_desert, London goldrush

These could be more tricky but worth a try:
ctf_poola with ctf_pool_v2
I see a mario_et but no idea how much different these 2 are

These aren't in the repository, you could try to search through forums likes SplatterLadder where some people used to do waypoints without taking the time to share them in the official repo...:
blitz_final, CaptureTheBox_R1, ea_base2, complex_b3, osiris_final, fp_jaden, kta_massacre, king_of_the_hill

Sadly forums are gone so no more "waypoint request" section, I myself have already several waypoints to finish, so I prefer not to take any new ones for now sorry ^^'

**Comment by Chucky-eng** [comment]
Thank you so much for your help on this I will give it a go and see if they
work  much appreciated

Cheers
Kerrie

**Comment by jswigart** [comment]
It's not an ideal sort of system, but I would accept github pull requests on new waypoints to add to the repository

**Comment by Chucky-eng** [comment]
where would i find to put the request as i would love some waypoints for
some maps that i cant seem to find

**Comment by plastovicka** [comment]
Write any requests to our new [forum](https://mygamingtalk.com/forums/forum/82-omnibot-development-and-discussion/).
Waypoints for **Enemy Territory** are stored in [Assembla SVN repository](http://svn.assembla.com/svn/omnibot/Enemy-Territory/0.8/et). There are folders nav and incomplete_navs. 
Waypoints for **Return to Castle Wolfenstein** are stored in [GitHub repository](https://github.com/jswigart/omni-bot/tree/stable/0.83/Installer/Files/rtcw).

**Comment by APGRoboCop** [comment]
Hello I'm trying to also create waypoints but for some odd reason try don't appear to show or aren't displayed ingame for some odd reason. I've managed to grab your old wiki pages from here:-

http://web.archive.org/web/20190929184409/http://omni-bot.invisionzone.com/wiki/index.php?title=Main_Page#tab=Getting_started

But when I used /bot waypoint_view on and /bot waypoint_add in ET it doesn't seem to work or maybe save the waypoints properly. Also the console said after using /bot waypoint_view on is:-

`Waypoint Visible on.
Cannot export drawing functions from cgame module.`

Don't know if this means that this current version of this game of ET (v2.60b) got some flaws or that with Omni-Bot 0.87.1

**Comment by Mateos81** [comment]
It's there: http://web.archive.org/web/20191024104104/http://omni-bot.invisionzone.com/wiki/index.php?title=Template:Basewaypointing

/bot waypoint_save

Be sure to run the OB mod!

Please post on forums instead of GitHub: https://mygamingtalk.com/forums/forum/82-omnibot-development-and-discussion/

**Comment by plastovicka** [comment]
> But when I used /bot waypoint_view on and /bot waypoint_add in ET it doesn't seem to work or maybe save the waypoints properly. Also the console said after using /bot waypoint_view on is:-
> 
> `Waypoint Visible on. Cannot export drawing functions from cgame module.`
> 
That means you have old version of cgame_mp_x86.dll. Have you downloaded [omni-bot_0_87_ET_waypoint_mod.zip](https://github.com/jswigart/omni-bot/releases) ? Why don't you use [ET:Legacy](https://www.etlegacy.com/) ? If you have old ET 2.60b, then you maybe also need to unzip files from omnibot_et.pk3.

**Comment by plastovicka** [comment]
Write any requests to the [forum](https://mygamingtalk.com/forums/forum/82-omnibot-development-and-discussion/).
