### ISSUE TITLE
Bot Weapon Profiles

### ISSUE THREAD

**Issue by BoredErica** [jswigart/omni-bot#18]
Sorry if this is a bad place to ask this. I've been trying to figure this out for a long time. How do I add a bot that uses a particular weapon every time for Wolfenstein: Enemy Territory?

-When I add bots via /bot addbot 1 1, I sometimes get names not defined in et_botnames_ext like "Omnibot[1]" and they don't follow the weapons I set in et_botnames_ext. Sometimes it adds bots with names defined in et_botnames_ext but for another class, so as a solider they use a random weapon.
-Is there a way manually add a specific bot using a specific bot weapon profile? I want to /bot addbot 1 1 Tanz and always get a soldier with flamethrower and /bot addbot 1 1 Grob and always get a solider with MG42, etc instead of leaving it to chance whether I get Tanz or Grob when adding bots without specifying a name.

**Comment by plastovicka** [comment]
- If you want to manually set classes and weapons, you have to disable the class manager.  
Insert line `global DisableClassManager = true;` in the file _omni-bot\et\scripts\et_autoexec_user.gm_.
- Preferred weapons require that bot names have ^o[BOT]^7 prefix:
`/bot addbot 1 1 ^o[BOT]^7Tanz`
`/bot addbot 1 1 ^o[BOT]^7Grog`
Then you can change weapons in file _et_botnames_ext.gm_:
`AxisBots["Tanz"] = { class=CLASS.SOLDIER, weapon=WEAPON.FLAMETHROWER, profile="" };`
`AxisBots["Grog"] = { class=CLASS.SOLDIER, weapon=WEAPON.PANZERFAUST, profile="" };`
-  Heavy weapons mortar and MG42 cannot be used as preferred weapons. Soldiers take these weapons automatically if there are any MOBILEMORTAR or MOBILEMG42 goals on a map.

**Comment by BoredErica** [comment]
So there will often be maps where the bots override the weapon profile and take a mobile MG42 or mortar due to map goals and there's nothing I can do apart from disabling MG42/mortar entirely?

**Comment by plastovicka** [comment]
If you don't like mortar or mobile MG42, you can disable them entirely:
`/bot minformortar 99`
`/bot minformobilemg 99`

**Comment by BoredErica** [comment]
I was hoping I could add bots that use MG42 and if a map has goals for deploying it while prone automatically do that but if not, just not use it and resort to using the secondary instead. If not then, thank you so much for the help so far. I've finally figured out how to get this up and running. :)
