### ISSUE TITLE
RTCW Omnibot - breaks IoRTCW widescreen

### ISSUE THREAD

**Issue by Arctures777** [jswigart/omni-bot#20]
Hi all,

I'm using the latest x64 version of iortcw 1.51c dated 16/03/19. This port comes with new cvars 'cg_fixedaspect' and 'cg_fixedaspectfov' so you can run the game in widescreen resolutions while maintaining the game's native aspect ratio so the weapon models aren't cut off. 

However when I run iortcw with omnibot this features does not work, the game still acknowledges the commands are set correctly but they don't take effect, what's weird is normally in iortcw you can set resolutions with different aspect ratios (4:3, 16:9 and 16:10) in the menu, however when running omnibot these aren't available and it reverts back to vanilla RTCW resolution choices.

It looks to me like the 64bit patch (omni-bot_0_87_RTCW_64bit.zip) needs updating to correspond with the latest changes in the iortcw release. I've duplicated the settings in the config files for both native iortcw and iortcw with omnibot and it still doesn't work.

Am I missing something or does something need updating on your end? Without the widescreen fix their is no point in playing Omnibot with iortcw for the time being.

**Comment by ensiform** [comment]
Is iortcw server built with omnibot by default? Is 64bit available for other platforms/games and omnibot?

**Comment by plastovicka** [comment]
If you want to run the game in widescreen resolutions, you must delete **omnibot_rtcw.pk3** and all **cgame_mp** and **ui_mp** DLLs from the omnibot folder. Then you will not be able to edit waypoints or use some omnibot cvars. But the game will be playable with bots.

**Comment by Arctures777** [comment]
Thanks for the quick reply that worked :) 

The widescreen takes effect after creating a game and not initially when launching the program, it says 'Omni-bot Version: 0.85' on the loading screen when creating the first game but it vanishes after creating every subsequent game, a few weird gimmicks but it works which is the most important xD

As for cvars, I'm only concerned with playing with bot difficulty settings at the moment so that's fine, out of curiosity which ones don't work as a result of this?

Also is their a place and point of contact to discuss the bot in general for future queries? I couldn't find any contact information in the readme and came across here as the only means of contact xD

**Comment by plastovicka** [comment]
The list of all omnibot CVARS is in readme.txt file which is inside the installation ZIP package. Cvars with **cg_** prefix don't work after deleting omnibot_rtcw.pk3.
A new discussion forum is now on https://mygamingtalk.com/forums/forum/82-omnibot-development-and-discussion/

**Comment by Arctures777** [comment]
Thank you.

I'd like to ask one last question which isn't necessarily related but it might avoid creating a thread on that forum, I will proceed to create a topic there if required.

The readme says Omnibot supports 99 maps and I can roughly count that amount looking at the map names in the 'nav' folder. 

Is their a convenient place where I can find all these or do I need to go hunting for each map via a search engine?

**Comment by Arctures777** [comment]
Thanks for the help :)
