### ISSUE TITLE
few things in omnibot rtcw 0.90

### ISSUE THREAD

**Issue by v1rkes** [jswigart/omni-bot#26]
![aas](https://github.com/jswigart/omni-bot/assets/86985617/ed4cae2b-8590-4dd4-b03b-0b8520aafec0)
i downloaded omnibot version 0.90 and you forgot to edit this img. i get this msg when a map is loading.
other curious thing is this after a round is finished.
![omnib](https://github.com/jswigart/omni-bot/assets/86985617/8bd0cb36-f667-4b9c-9861-2e276f31a691)
**g_unlockWeapons**
_Unlock all weapons for all classes
default 0, 1 to unlock weapons_
with this cmd medic, engies shouldn't drop their weapon right? but is not working if u can check.

**Comment by plastovicka** [comment]
Startup screen image is displayed by the mod. It's in package **omnibot_rtcw.pk3** which is downloaded to clients. Last version of the mod is 0.85 which was released in 2015.

If **g_unlockWeapons** is 1, then soldiers can drop their weapon (mauser, flamethrower, venom) and everybody can pick it up.

**Comment by v1rkes** [comment]
![image](https://github.com/jswigart/omni-bot/assets/86985617/14d141b0-ddaa-46be-a30b-bcfba0a156dd)


> Last version of the mod is 0.85 which was released in 2015.

**Comment by plastovicka** [comment]
There are two folders in the installation package:
1. **omni-bot** - it controls bots' behavior, movement, shooting and goals. Console commands must begin with **\bot** prefix. Last version is 0.9.
2. **omnibot** - it's a mod which modifies the game rules, weapons, players skills, menus, textures and sounds. It is configured by **cvars**. Last version is 0.85.

The omni-bot folder is required to run bots. The omnibot folder is optional and can be replaced by another compatible mod, for example s4ndmod. Many servers use own mods which are customized for their clan.
