### ISSUE TITLE
Incompatibility with Iortcw resolutions and commands

### ISSUE THREAD

**Issue by OverPro123** [jswigart/omni-bot#28]
Resolution can go up only to 1600*1200, and also command fix for broken fov is not working : 
/cg_fixedaspect 2. In iortcw mp, this command works fine until I launch this mod, when I do that, game reverts to broken fov and when I type command in console and restart, nothing changes.

**Comment by ensiform** [comment]
Because you're comparing running two different mods, the ommibot bot dev "mod" is separate from iortcw's base mod.

**Comment by OverPro123** [comment]
Yeah I just figured it out, now I would like this thread to be deleted lol.

**Comment by ensiform** [comment]
You should be able to just close the issue yourself since you opened it.
