### ISSUE TITLE
Invalid use of sizeof division on pointer in RTCW_InterfaceFuncs.cpp

### ISSUE THREAD

**Issue by ensiform** [jswigart/omni-bot#30]
https://github.com/jswigart/omni-bot/blob/7bf5296c33004f8ae550036b141c7fcfbb7f0aba/0.83/Omnibot/RTCW/RTCW_InterfaceFuncs.cpp#L12-L13

Both of these struct members are pointers which makes this operation not valid as it uses the pointer size and not the size of an array which was probably expected to be an array. Would require changing the structs and new RTCW mod update to reflect changes as well. Target name could probably be capped at 64 or something less like 36-40 since MAX_NETNAME in mods is usually 36.

**Comment by plastovicka** [comment]
fixed by a5a1027262c46c0a4d33193a016ba8c21153fac0
