### ISSUE TITLE
Bots keep trying to destroy unvulnerable truck on etl_supply_v4

### ISSUE THREAD

**Issue by Jopacari** [jswigart/omni-bot#31]
Hi.
I have the map script for etl_supply_v4 configured for the truck to be invulnerable:

`setdamagable truck 0					// Make truck invulnerable`

But AXIS bots keep trying to destroy it throwing grenades and most of the time they are harming themselves and the rest of the team doing so.

I would expect that the bot do not try to destroy and entity that is invulnerable.
Any suggestion?

Thanks
JP

**Comment by plastovicka** [comment]
Add this function to the file omni-bot/et/nav/etl_supply_v4.gm:
```
global OnBotJoin = function(bot)
{
	if (bot.GetTeam() == TEAM.AXIS)
	{
		Util.IgnoreTargetGoal( bot, "MOVER_truck" );
	}
};
```

**Comment by Jopacari** [comment]
Hi, @plastovicka .

Thank you for your quick answer but it didn't fix the issue. The axis bots keep throwing grenades to try to destroy the truck.
Any other suggestion?

**Comment by plastovicka** [comment]
Do you run ET locally on your computer or on a dedicated server ? The file has to be modified on the server. Then you have to restart the map.

**Comment by Jopacari** [comment]
I run a dedicated server and it was restarted after changing the file.

**Comment by pinickitty** [comment]
Can you also confirm which mod the server is running and also which binaries so I can try and replicate

**Comment by Jopacari** [comment]
It is running mod legacy.
I have the latest version: 2.83.1 linux.
I attached the files I am using to run it.
[etl_supply_v4.zip](https://github.com/user-attachments/files/17959195/etl_supply_v4.zip)
I hope it helps.

JP

**Comment by pinickitty** [comment]
I tried with the modified gm file too and still the axis bots attack the truck so will need a different solution. I'll read through the gm and goal file and see if I can spot anything too.

**Comment by plastovicka** [comment]
> I attached the files I am using to run it. [etl_supply_v4.zip](https://github.com/user-attachments/files/17959195/etl_supply_v4.zip) 

There is an empty OnBotJoin function on line 848. You have to delete it.

**Comment by Jopacari** [comment]
I will try and give feedback. 
Thank you

**Comment by Jopacari** [comment]
It worked.
Thank you. 👍
